-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUuFByo2PICpczq+q
LOh0USzWoPRg/Hs1WdWsWTKSeAqgCgYIKoZIzj0DAQehRANCAARkFb9bMeCX7QE2
O8AYq8bwD5wYpsEtIPtMhIc4q89kh8egBniJITCecF/q2IXdUEKLqSxK14B7jpsX
cxKAcBkG
-----END PRIVATE KEY-----